# Generated by Django 4.2 on 2023-05-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messageTimeStamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
