# Generated by Django 4.2 on 2023-05-04 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_message_messagetimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messageTimeStamp',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
