# Generated by Django 4.2 on 2023-05-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_message_messagetimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messageTimeStamp',
            field=models.TimeField(blank=True, default='Thu May  4 10:12:51 2023'),
        ),
    ]
